-- MySQL Script generated by MySQL Workbench
-- Thu Oct 23 17:17:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`classes_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes_usuarios` (
  `id_classe_usuario` INT NOT NULL,
  `nome_classe_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_classe_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `nome_usuario` VARCHAR(50) NOT NULL,
  `sobrenome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(70) NOT NULL,
  `classes_usuarios_id_classe_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `classes_usuarios_id_classe_usuario`),
  INDEX `fk_usuarios_classes_usuarios1_idx` (`classes_usuarios_id_classe_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_classes_usuarios1`
    FOREIGN KEY (`classes_usuarios_id_classe_usuario`)
    REFERENCES `mydb`.`classes_usuarios` (`id_classe_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status_porte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_porte` (
  `id_status_porte` INT NOT NULL,
  `name_status_porte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status_porte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_porte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_porte` (
  `id_tipo_porte` INT NOT NULL,
  `nome_tipo_porte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_porte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abrangencia_porte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abrangencia_porte` (
  `id_abrangencia_porte` INT NOT NULL,
  `nome_abrangencia_porte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_abrangencia_porte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especies_arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especies_arma` (
  `id_especie_arma` INT NOT NULL,
  `nome_especie_arma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_especie_arma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marcas_arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marcas_arma` (
  `id_marca_arma` INT NOT NULL,
  `nome_marca_arma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca_arma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calibres_arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calibres_arma` (
  `id_calibre_arma` INT NOT NULL,
  `nome_calibre_armacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_calibre_arma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sexos_portador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sexos_portador` (
  `id_sexo_portador` INT NOT NULL,
  `nome_sexo_portador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sexo_portador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`armas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`armas` (
  `id_arma` INT NOT NULL,
  `marcas_arma_id_marca_arma` INT NOT NULL,
  `calibres_arma_id_calibre_arma` INT NOT NULL,
  `especies_arma_id_especie_arma` INT NOT NULL,
  `quantidade_armas` INT NOT NULL,
  PRIMARY KEY (`id_arma`),
  INDEX `fk_armas_calibres_arma1_idx` (`calibres_arma_id_calibre_arma` ASC) VISIBLE,
  INDEX `fk_armas_especies_arma1_idx` (`especies_arma_id_especie_arma` ASC) VISIBLE,
  CONSTRAINT `fk_armas_marcas_arma`
    FOREIGN KEY (`marcas_arma_id_marca_arma`)
    REFERENCES `mydb`.`marcas_arma` (`id_marca_arma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armas_calibres_arma1`
    FOREIGN KEY (`calibres_arma_id_calibre_arma`)
    REFERENCES `mydb`.`calibres_arma` (`id_calibre_arma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_armas_especies_arma1`
    FOREIGN KEY (`especies_arma_id_especie_arma`)
    REFERENCES `mydb`.`especies_arma` (`id_especie_arma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uf` (
  `id_uf` INT NOT NULL,
  `nome_uf` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_uf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`portes` (
  `id_portes` INT NOT NULL,
  `status_porte_id_status_porte` INT NOT NULL,
  `tipos_porte_id_tipo_porte` INT NOT NULL,
  `abrangencia_porte_id_abrangencia_porte` INT NOT NULL,
  `sexos_portador_id_sexo_portador` INT NOT NULL,
  `armas_id_arma` INT NOT NULL,
  `uf_id_uf` INT NOT NULL,
  `ano_emissao_porte` DATE NOT NULL,
  `mes_emissao_porte` DATE NOT NULL,
  PRIMARY KEY (`id_portes`, `armas_id_arma`),
  INDEX `fk_portes_status_porte1_idx` (`status_porte_id_status_porte` ASC) VISIBLE,
  INDEX `fk_portes_tipos_porte1_idx` (`tipos_porte_id_tipo_porte` ASC) VISIBLE,
  INDEX `fk_portes_abrangencia_porte1_idx` (`abrangencia_porte_id_abrangencia_porte` ASC) VISIBLE,
  INDEX `fk_portes_sexos_portador1_idx` (`sexos_portador_id_sexo_portador` ASC) VISIBLE,
  INDEX `fk_portes_armas1_idx` (`armas_id_arma` ASC) VISIBLE,
  INDEX `fk_portes_uf1_idx` (`uf_id_uf` ASC) VISIBLE,
  CONSTRAINT `fk_portes_status_porte1`
    FOREIGN KEY (`status_porte_id_status_porte`)
    REFERENCES `mydb`.`status_porte` (`id_status_porte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portes_tipos_porte1`
    FOREIGN KEY (`tipos_porte_id_tipo_porte`)
    REFERENCES `mydb`.`tipos_porte` (`id_tipo_porte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portes_abrangencia_porte1`
    FOREIGN KEY (`abrangencia_porte_id_abrangencia_porte`)
    REFERENCES `mydb`.`abrangencia_porte` (`id_abrangencia_porte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portes_sexos_portador1`
    FOREIGN KEY (`sexos_portador_id_sexo_portador`)
    REFERENCES `mydb`.`sexos_portador` (`id_sexo_portador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portes_armas1`
    FOREIGN KEY (`armas_id_arma`)
    REFERENCES `mydb`.`armas` (`id_arma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_portes_uf1`
    FOREIGN KEY (`uf_id_uf`)
    REFERENCES `mydb`.`uf` (`id_uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
