"""VERSION 2

Revision ID: d44c56077a4c
Revises: b5777dcea088
Create Date: 2025-10-23 22:18:27.713203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44c56077a4c'
down_revision: Union[str, Sequence[str], None] = 'b5777dcea088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portes', sa.Column('ano_emissao', sa.Integer(), nullable=False))
    op.add_column('portes', sa.Column('mes_emissao', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portes', 'mes_emissao')
    op.drop_column('portes', 'ano_emissao')
    # ### end Alembic commands ###
