"""VERSION 3

Revision ID: f1bc85194c2e
Revises: d44c56077a4c
Create Date: 2025-10-24 18:43:59.214665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bc85194c2e'
down_revision: Union[str, Sequence[str], None] = 'd44c56077a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw')
    op.drop_constraint(None, 'portes', type_='foreignkey')
    op.drop_column('portes', 'id_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portes', sa.Column('id_usuario', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'portes', 'usuarios', ['id_usuario'], ['id'])
    op.create_table('raw',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ano_emissao', sa.NUMERIC(), nullable=True),
    sa.Column('mes_emissao', sa.INTEGER(), nullable=True),
    sa.Column('UF', sa.VARCHAR(length=5), nullable=True),
    sa.Column('MUNICIPIO', sa.VARCHAR(length=45), nullable=True),
    sa.Column('TIPO', sa.VARCHAR(length=45), nullable=True),
    sa.Column('STATUS', sa.VARCHAR(length=45), nullable=True),
    sa.Column('ABRANGENCIA', sa.VARCHAR(length=45), nullable=True),
    sa.Column('ESPECIE_ARMA', sa.VARCHAR(length=45), nullable=True),
    sa.Column('MARCA_ARMA', sa.VARCHAR(length=45), nullable=True),
    sa.Column('CALIBRE_ARMA', sa.VARCHAR(length=45), nullable=True),
    sa.Column('SEXO', sa.VARCHAR(length=45), nullable=True),
    sa.Column('TOTAL', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
